### ISSUE TITLE
DUDE THIS IS AWESOME

### ISSUE THREAD

**Issue by niftylettuce** [JamesFator/BTHSControl#4]
Where can I make a donation?

See https://github.com/clementine-player/Clementine/issues/3262

**Comment by JamesFator** [comment]
Thank you! A few people have asked, so I set up a donation link on [my website](http://jamesfator.com/blog/about-me/), but it's not at all required. I'm happy as long as people have access to a solution!

**Comment by ramonpoca** [comment]
You made my day happier!
Great job! Thank you!
