### ISSUE TITLE
Does not work on El Capitan

### ISSUE THREAD

**Issue by Rambro101** [JamesFator/BTHSControl#8]
Hey, I was very interested in your project as I own a bluetooth headset with auto play and pause (based on when u remove your headset). This means that iTunes keeps popping up every so often which is a huge pain. I was looking at solutions to this problem and I came across your app. However, it doesnt seem to work on my 2015 Macbook Pro 13' running El Capitan. I don't mind disabling SIP in order to get this working either.

**Comment by JamesFator** [comment]
Hey Rambro101, I patched it to hopefully work with El Capitan, but you'll have to reinstall it. So download the new version, then re-run the installation as documented in the readme. Let me know how it goes and I'll help from there.

**Comment by Rambro101** [comment]
It works on vlc now!! :+1: 

It still keeps opening up iTunes whenever Im not using VLC, though. Do you think its possible to enable the play/pause feature only when a supported app is open?
