### ISSUE TITLE
AVRCPAgent crash on El Capitan

### ISSUE THREAD

**Issue by ev0rtex** [JamesFator/BTHSControl#9]
I have tried several times to get this to run now that I've upgraded to 10.11 and simply cannot get it to work. I have run these commands repeatedly just in case there something left behind somewhere:
```sh
sudo ./install.sh uninstall old
sudo ./install.sh uninstall
sudo rm -r build
sudo ./install.sh install
```
After I connect my BT headphones and try pressing the play/pause button I get the following in my system log:
```
10/19/15 11:11:54.010 AM com.apple.xpc.launchd[1]: (com.bths.AVRCPAgent[91875]) Service exited due to signal: Abort trap: 6
10/19/15 11:11:54.019 AM com.apple.xpc.launchd[1]: (com.apple.ReportCrash.Root[92017]) Endpoint has been activated through legacy launch(3) APIs. Please switch to XPC or bootstrap_check_in(): com.apple.ReportCrash.DirectoryService
10/19/15 11:11:54.740 AM ReportCrash[92017]: Saved crash report for AVRCPAgent[91875] version 1.0 (1) to /Library/Logs/DiagnosticReports/AVRCPAgent_2015-10-19-111154_Shadow.crash
```
I am at my wits end on getting this to work again. Attached you will find the log mentioned above. You can find the above-mentioned crash report in [this gist](https://gist.github.com/ev0rtex/c36c470ccaf82274fa62).

**Comment by JamesFator** [comment]
Run the uninstall again with sudo because you ran install with sudo
    sudo ./install.sh uninstall
Then run install without sudo because it needs to execute some things as you.
    ./install.sh install
It may still ask for your password because it runs sudo commands inside of it. It's probably not a correct way to make an install script, but that's the way we have it.

Let me know how that goes.

**Comment by ev0rtex** [comment]
Well...I actually did try that before but ran into an issue where it didn't actually install. Relevant build/install output when I run `./install.sh install` as my user (after having run `sudo ./install.sh uninstall`):
```
.
.
.
** BUILD SUCCEEDED **

cp: ./AVRCPAgent/PlugIns/BTHSControl.bundle/Contents/Info.plist: Permission denied
cp: ./AVRCPAgent/PlugIns/BTHSControl.bundle/Contents/MacOS/BTHSControl: Permission denied
cp: ./AVRCPAgent/PlugIns/BTHSControl.bundle/Contents/Resources/en.lproj/InfoPlist.strings: Permission denied
```
I'm assuming at this point it's supposed to be copying everything to `/Library/Services/`. After those failed `cp` lines it doesn't actually have anything set up in `/Library/Services/` like it does when run as root.

**Comment by ev0rtex** [comment]
FYI, I solved my problems by deleting and cloning the repo again. I guess the permission issues were with those files it tried to copy rather than with anything on the system.
